// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package wafservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// This is an example service which we will be using as a place holder till we
// light up a service on AzWaf.
type Service struct {
	ServiceConfigId      string       `protobuf:"bytes,1,opt,name=serviceConfigId,proto3" json:"serviceConfigId,omitempty"`
	Config               *ConfigDummy `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_37981b6fcfdd6df9, []int{0}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetServiceConfigId() string {
	if m != nil {
		return m.ServiceConfigId
	}
	return ""
}

func (m *Service) GetConfig() *ConfigDummy {
	if m != nil {
		return m.Config
	}
	return nil
}

//
// A representation of AzWaf configuration.
type Config struct {
	ServiceConfig        []*Service `protobuf:"bytes,1,rep,name=serviceConfig,proto3" json:"serviceConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_37981b6fcfdd6df9, []int{1}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetServiceConfig() []*Service {
	if m != nil {
		return m.ServiceConfig
	}
	return nil
}

type ConfigDummy struct {
	// Types that are valid to be assigned to Message:
	//	*ConfigDummy_SecRuleConfig
	//	*ConfigDummy_GeoDbConfig
	//	*ConfigDummy_IpReputationConfig
	Message              isConfigDummy_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ConfigDummy) Reset()         { *m = ConfigDummy{} }
func (m *ConfigDummy) String() string { return proto.CompactTextString(m) }
func (*ConfigDummy) ProtoMessage()    {}
func (*ConfigDummy) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_37981b6fcfdd6df9, []int{2}
}
func (m *ConfigDummy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigDummy.Unmarshal(m, b)
}
func (m *ConfigDummy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigDummy.Marshal(b, m, deterministic)
}
func (dst *ConfigDummy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigDummy.Merge(dst, src)
}
func (m *ConfigDummy) XXX_Size() int {
	return xxx_messageInfo_ConfigDummy.Size(m)
}
func (m *ConfigDummy) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigDummy.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigDummy proto.InternalMessageInfo

type isConfigDummy_Message interface {
	isConfigDummy_Message()
}

type ConfigDummy_SecRuleConfig struct {
	SecRuleConfig *SecRuleConfigDummy `protobuf:"bytes,1,opt,name=secRuleConfig,proto3,oneof"`
}

type ConfigDummy_GeoDbConfig struct {
	GeoDbConfig *GeoDbConfigDummy `protobuf:"bytes,2,opt,name=geoDbConfig,proto3,oneof"`
}

type ConfigDummy_IpReputationConfig struct {
	IpReputationConfig *IPReputationConfigDummy `protobuf:"bytes,3,opt,name=ipReputationConfig,proto3,oneof"`
}

func (*ConfigDummy_SecRuleConfig) isConfigDummy_Message() {}

func (*ConfigDummy_GeoDbConfig) isConfigDummy_Message() {}

func (*ConfigDummy_IpReputationConfig) isConfigDummy_Message() {}

func (m *ConfigDummy) GetMessage() isConfigDummy_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ConfigDummy) GetSecRuleConfig() *SecRuleConfigDummy {
	if x, ok := m.GetMessage().(*ConfigDummy_SecRuleConfig); ok {
		return x.SecRuleConfig
	}
	return nil
}

func (m *ConfigDummy) GetGeoDbConfig() *GeoDbConfigDummy {
	if x, ok := m.GetMessage().(*ConfigDummy_GeoDbConfig); ok {
		return x.GeoDbConfig
	}
	return nil
}

func (m *ConfigDummy) GetIpReputationConfig() *IPReputationConfigDummy {
	if x, ok := m.GetMessage().(*ConfigDummy_IpReputationConfig); ok {
		return x.IpReputationConfig
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ConfigDummy) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ConfigDummy_OneofMarshaler, _ConfigDummy_OneofUnmarshaler, _ConfigDummy_OneofSizer, []interface{}{
		(*ConfigDummy_SecRuleConfig)(nil),
		(*ConfigDummy_GeoDbConfig)(nil),
		(*ConfigDummy_IpReputationConfig)(nil),
	}
}

func _ConfigDummy_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ConfigDummy)
	// message
	switch x := m.Message.(type) {
	case *ConfigDummy_SecRuleConfig:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SecRuleConfig); err != nil {
			return err
		}
	case *ConfigDummy_GeoDbConfig:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GeoDbConfig); err != nil {
			return err
		}
	case *ConfigDummy_IpReputationConfig:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IpReputationConfig); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ConfigDummy.Message has unexpected type %T", x)
	}
	return nil
}

func _ConfigDummy_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ConfigDummy)
	switch tag {
	case 1: // message.secRuleConfig
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SecRuleConfigDummy)
		err := b.DecodeMessage(msg)
		m.Message = &ConfigDummy_SecRuleConfig{msg}
		return true, err
	case 2: // message.geoDbConfig
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GeoDbConfigDummy)
		err := b.DecodeMessage(msg)
		m.Message = &ConfigDummy_GeoDbConfig{msg}
		return true, err
	case 3: // message.ipReputationConfig
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IPReputationConfigDummy)
		err := b.DecodeMessage(msg)
		m.Message = &ConfigDummy_IpReputationConfig{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ConfigDummy_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ConfigDummy)
	// message
	switch x := m.Message.(type) {
	case *ConfigDummy_SecRuleConfig:
		s := proto.Size(x.SecRuleConfig)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ConfigDummy_GeoDbConfig:
		s := proto.Size(x.GeoDbConfig)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ConfigDummy_IpReputationConfig:
		s := proto.Size(x.IpReputationConfig)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SecRuleConfigDummy struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecRuleConfigDummy) Reset()         { *m = SecRuleConfigDummy{} }
func (m *SecRuleConfigDummy) String() string { return proto.CompactTextString(m) }
func (*SecRuleConfigDummy) ProtoMessage()    {}
func (*SecRuleConfigDummy) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_37981b6fcfdd6df9, []int{3}
}
func (m *SecRuleConfigDummy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecRuleConfigDummy.Unmarshal(m, b)
}
func (m *SecRuleConfigDummy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecRuleConfigDummy.Marshal(b, m, deterministic)
}
func (dst *SecRuleConfigDummy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecRuleConfigDummy.Merge(dst, src)
}
func (m *SecRuleConfigDummy) XXX_Size() int {
	return xxx_messageInfo_SecRuleConfigDummy.Size(m)
}
func (m *SecRuleConfigDummy) XXX_DiscardUnknown() {
	xxx_messageInfo_SecRuleConfigDummy.DiscardUnknown(m)
}

var xxx_messageInfo_SecRuleConfigDummy proto.InternalMessageInfo

func (m *SecRuleConfigDummy) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type GeoDbConfigDummy struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeoDbConfigDummy) Reset()         { *m = GeoDbConfigDummy{} }
func (m *GeoDbConfigDummy) String() string { return proto.CompactTextString(m) }
func (*GeoDbConfigDummy) ProtoMessage()    {}
func (*GeoDbConfigDummy) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_37981b6fcfdd6df9, []int{4}
}
func (m *GeoDbConfigDummy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoDbConfigDummy.Unmarshal(m, b)
}
func (m *GeoDbConfigDummy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoDbConfigDummy.Marshal(b, m, deterministic)
}
func (dst *GeoDbConfigDummy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoDbConfigDummy.Merge(dst, src)
}
func (m *GeoDbConfigDummy) XXX_Size() int {
	return xxx_messageInfo_GeoDbConfigDummy.Size(m)
}
func (m *GeoDbConfigDummy) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoDbConfigDummy.DiscardUnknown(m)
}

var xxx_messageInfo_GeoDbConfigDummy proto.InternalMessageInfo

func (m *GeoDbConfigDummy) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type IPReputationConfigDummy struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPReputationConfigDummy) Reset()         { *m = IPReputationConfigDummy{} }
func (m *IPReputationConfigDummy) String() string { return proto.CompactTextString(m) }
func (*IPReputationConfigDummy) ProtoMessage()    {}
func (*IPReputationConfigDummy) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_37981b6fcfdd6df9, []int{5}
}
func (m *IPReputationConfigDummy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPReputationConfigDummy.Unmarshal(m, b)
}
func (m *IPReputationConfigDummy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPReputationConfigDummy.Marshal(b, m, deterministic)
}
func (dst *IPReputationConfigDummy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPReputationConfigDummy.Merge(dst, src)
}
func (m *IPReputationConfigDummy) XXX_Size() int {
	return xxx_messageInfo_IPReputationConfigDummy.Size(m)
}
func (m *IPReputationConfigDummy) XXX_DiscardUnknown() {
	xxx_messageInfo_IPReputationConfigDummy.DiscardUnknown(m)
}

var xxx_messageInfo_IPReputationConfigDummy proto.InternalMessageInfo

func (m *IPReputationConfigDummy) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func init() {
	proto.RegisterType((*Service)(nil), "wafservice.Service")
	proto.RegisterType((*Config)(nil), "wafservice.Config")
	proto.RegisterType((*ConfigDummy)(nil), "wafservice.ConfigDummy")
	proto.RegisterType((*SecRuleConfigDummy)(nil), "wafservice.SecRuleConfigDummy")
	proto.RegisterType((*GeoDbConfigDummy)(nil), "wafservice.GeoDbConfigDummy")
	proto.RegisterType((*IPReputationConfigDummy)(nil), "wafservice.IPReputationConfigDummy")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_config_37981b6fcfdd6df9) }

var fileDescriptor_config_37981b6fcfdd6df9 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd2, 0x41, 0x4b, 0x84, 0x40,
	0x14, 0x07, 0xf0, 0xa6, 0x05, 0x6d, 0x9f, 0x45, 0xf1, 0x3a, 0xac, 0x87, 0x08, 0x99, 0x2e, 0x1e,
	0xc2, 0x60, 0xf7, 0xd4, 0x2d, 0x72, 0xa9, 0xf6, 0x16, 0x13, 0x7d, 0x00, 0x75, 0xdf, 0x8a, 0xb0,
	0x3a, 0xb2, 0x6a, 0xd1, 0x47, 0xef, 0x16, 0xeb, 0x28, 0xce, 0x58, 0xdb, 0x4d, 0x9f, 0xff, 0xf7,
	0xe3, 0x3f, 0x38, 0x70, 0x9a, 0xc8, 0x62, 0x93, 0xa5, 0x41, 0xb9, 0x93, 0xb5, 0x44, 0xf8, 0x8c,
	0x36, 0x15, 0xed, 0x3e, 0xb2, 0x84, 0xf8, 0x1a, 0xec, 0x37, 0xf5, 0x88, 0x3e, 0x9c, 0x77, 0xd3,
	0xb0, 0x4d, 0xaf, 0xd6, 0x2e, 0xf3, 0x98, 0x3f, 0x15, 0xe3, 0x31, 0xde, 0x81, 0xa5, 0x40, 0xf7,
	0xd8, 0x63, 0xbe, 0x33, 0x9f, 0x05, 0x83, 0x18, 0xa8, 0xd4, 0xb2, 0xc9, 0xf3, 0x2f, 0xd1, 0xc5,
	0x78, 0x08, 0x96, 0x1a, 0xe3, 0x3d, 0x9c, 0x19, 0x9a, 0xcb, 0xbc, 0x89, 0xef, 0xcc, 0x2f, 0x75,
	0xa1, 0x2b, 0x24, 0xcc, 0x24, 0xff, 0x66, 0xe0, 0x68, 0x38, 0x3e, 0xed, 0xa9, 0x44, 0x34, 0xdb,
	0x81, 0xda, 0x97, 0xb9, 0x36, 0x29, 0x2d, 0xd0, 0xae, 0xbd, 0x1c, 0x09, 0x73, 0x0d, 0x1f, 0xc0,
	0x49, 0x49, 0x2e, 0xe3, 0x50, 0x3f, 0xd2, 0x95, 0xae, 0x3c, 0x0f, 0x9f, 0x7b, 0x43, 0x5f, 0xc1,
	0x77, 0xc0, 0xac, 0x14, 0x54, 0x36, 0x75, 0x54, 0x67, 0xb2, 0xe8, 0xa0, 0x49, 0x0b, 0xdd, 0xe8,
	0xd0, 0xea, 0x75, 0x9c, 0xea, 0xbd, 0x3f, 0x80, 0xc7, 0x29, 0xd8, 0x39, 0x55, 0x55, 0x94, 0x12,
	0x0f, 0x00, 0x7f, 0x1f, 0x05, 0x5d, 0xb0, 0xa9, 0x88, 0xe2, 0x2d, 0xa9, 0x3f, 0x75, 0x22, 0xfa,
	0x57, 0x7e, 0x0b, 0x17, 0xe3, 0xd2, 0xff, 0xa4, 0x17, 0x30, 0x3b, 0xd0, 0xec, 0xf0, 0x52, 0x6c,
	0xb5, 0x97, 0x69, 0xf1, 0x13, 0x00, 0x00, 0xff, 0xff, 0x55, 0x5d, 0xbc, 0xcb, 0x5c, 0x02, 0x00,
	0x00,
}
