// Code generated by protoc-gen-go. DO NOT EDIT.
// source: waf.proto

package wafservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HeaderPair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeaderPair) Reset()         { *m = HeaderPair{} }
func (m *HeaderPair) String() string { return proto.CompactTextString(m) }
func (*HeaderPair) ProtoMessage()    {}
func (*HeaderPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{0}
}
func (m *HeaderPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderPair.Unmarshal(m, b)
}
func (m *HeaderPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderPair.Marshal(b, m, deterministic)
}
func (dst *HeaderPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderPair.Merge(dst, src)
}
func (m *HeaderPair) XXX_Size() int {
	return xxx_messageInfo_HeaderPair.Size(m)
}
func (m *HeaderPair) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderPair.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderPair proto.InternalMessageInfo

func (m *HeaderPair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HeaderPair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type WafHttpRequest struct {
	// Types that are valid to be assigned to Content:
	//	*WafHttpRequest_HeadersAndFirstChunk
	//	*WafHttpRequest_NextBodyChunk
	Content              isWafHttpRequest_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *WafHttpRequest) Reset()         { *m = WafHttpRequest{} }
func (m *WafHttpRequest) String() string { return proto.CompactTextString(m) }
func (*WafHttpRequest) ProtoMessage()    {}
func (*WafHttpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{1}
}
func (m *WafHttpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WafHttpRequest.Unmarshal(m, b)
}
func (m *WafHttpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WafHttpRequest.Marshal(b, m, deterministic)
}
func (dst *WafHttpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WafHttpRequest.Merge(dst, src)
}
func (m *WafHttpRequest) XXX_Size() int {
	return xxx_messageInfo_WafHttpRequest.Size(m)
}
func (m *WafHttpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WafHttpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WafHttpRequest proto.InternalMessageInfo

type isWafHttpRequest_Content interface {
	isWafHttpRequest_Content()
}

type WafHttpRequest_HeadersAndFirstChunk struct {
	HeadersAndFirstChunk *HeadersAndFirstChunk `protobuf:"bytes,1,opt,name=headersAndFirstChunk,proto3,oneof"`
}

type WafHttpRequest_NextBodyChunk struct {
	NextBodyChunk *NextBodyChunk `protobuf:"bytes,2,opt,name=nextBodyChunk,proto3,oneof"`
}

func (*WafHttpRequest_HeadersAndFirstChunk) isWafHttpRequest_Content() {}

func (*WafHttpRequest_NextBodyChunk) isWafHttpRequest_Content() {}

func (m *WafHttpRequest) GetContent() isWafHttpRequest_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *WafHttpRequest) GetHeadersAndFirstChunk() *HeadersAndFirstChunk {
	if x, ok := m.GetContent().(*WafHttpRequest_HeadersAndFirstChunk); ok {
		return x.HeadersAndFirstChunk
	}
	return nil
}

func (m *WafHttpRequest) GetNextBodyChunk() *NextBodyChunk {
	if x, ok := m.GetContent().(*WafHttpRequest_NextBodyChunk); ok {
		return x.NextBodyChunk
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*WafHttpRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _WafHttpRequest_OneofMarshaler, _WafHttpRequest_OneofUnmarshaler, _WafHttpRequest_OneofSizer, []interface{}{
		(*WafHttpRequest_HeadersAndFirstChunk)(nil),
		(*WafHttpRequest_NextBodyChunk)(nil),
	}
}

func _WafHttpRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*WafHttpRequest)
	// content
	switch x := m.Content.(type) {
	case *WafHttpRequest_HeadersAndFirstChunk:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HeadersAndFirstChunk); err != nil {
			return err
		}
	case *WafHttpRequest_NextBodyChunk:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NextBodyChunk); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("WafHttpRequest.Content has unexpected type %T", x)
	}
	return nil
}

func _WafHttpRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*WafHttpRequest)
	switch tag {
	case 1: // content.headersAndFirstChunk
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HeadersAndFirstChunk)
		err := b.DecodeMessage(msg)
		m.Content = &WafHttpRequest_HeadersAndFirstChunk{msg}
		return true, err
	case 2: // content.nextBodyChunk
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NextBodyChunk)
		err := b.DecodeMessage(msg)
		m.Content = &WafHttpRequest_NextBodyChunk{msg}
		return true, err
	default:
		return false, nil
	}
}

func _WafHttpRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*WafHttpRequest)
	// content
	switch x := m.Content.(type) {
	case *WafHttpRequest_HeadersAndFirstChunk:
		s := proto.Size(x.HeadersAndFirstChunk)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WafHttpRequest_NextBodyChunk:
		s := proto.Size(x.NextBodyChunk)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type HeadersAndFirstChunk struct {
	RemoteAddr           string              `protobuf:"bytes,9,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	ConfigID             string              `protobuf:"bytes,7,opt,name=configID,proto3" json:"configID,omitempty"`
	MetaData             *RequestLogMetaData `protobuf:"bytes,8,opt,name=metaData,proto3" json:"metaData,omitempty"`
	Method               string              `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Uri                  string              `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Headers              []*HeaderPair       `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	FirstBodyChunk       []byte              `protobuf:"bytes,4,opt,name=firstBodyChunk,proto3" json:"firstBodyChunk,omitempty"`
	MoreBodyChunks       bool                `protobuf:"varint,5,opt,name=moreBodyChunks,proto3" json:"moreBodyChunks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HeadersAndFirstChunk) Reset()         { *m = HeadersAndFirstChunk{} }
func (m *HeadersAndFirstChunk) String() string { return proto.CompactTextString(m) }
func (*HeadersAndFirstChunk) ProtoMessage()    {}
func (*HeadersAndFirstChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{2}
}
func (m *HeadersAndFirstChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeadersAndFirstChunk.Unmarshal(m, b)
}
func (m *HeadersAndFirstChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeadersAndFirstChunk.Marshal(b, m, deterministic)
}
func (dst *HeadersAndFirstChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeadersAndFirstChunk.Merge(dst, src)
}
func (m *HeadersAndFirstChunk) XXX_Size() int {
	return xxx_messageInfo_HeadersAndFirstChunk.Size(m)
}
func (m *HeadersAndFirstChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_HeadersAndFirstChunk.DiscardUnknown(m)
}

var xxx_messageInfo_HeadersAndFirstChunk proto.InternalMessageInfo

func (m *HeadersAndFirstChunk) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *HeadersAndFirstChunk) GetConfigID() string {
	if m != nil {
		return m.ConfigID
	}
	return ""
}

func (m *HeadersAndFirstChunk) GetMetaData() *RequestLogMetaData {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *HeadersAndFirstChunk) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HeadersAndFirstChunk) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *HeadersAndFirstChunk) GetHeaders() []*HeaderPair {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HeadersAndFirstChunk) GetFirstBodyChunk() []byte {
	if m != nil {
		return m.FirstBodyChunk
	}
	return nil
}

func (m *HeadersAndFirstChunk) GetMoreBodyChunks() bool {
	if m != nil {
		return m.MoreBodyChunks
	}
	return false
}

type RequestLogMetaData struct {
	Scope                string   `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	ScopeName            string   `protobuf:"bytes,2,opt,name=scopeName,proto3" json:"scopeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestLogMetaData) Reset()         { *m = RequestLogMetaData{} }
func (m *RequestLogMetaData) String() string { return proto.CompactTextString(m) }
func (*RequestLogMetaData) ProtoMessage()    {}
func (*RequestLogMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{3}
}
func (m *RequestLogMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestLogMetaData.Unmarshal(m, b)
}
func (m *RequestLogMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestLogMetaData.Marshal(b, m, deterministic)
}
func (dst *RequestLogMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLogMetaData.Merge(dst, src)
}
func (m *RequestLogMetaData) XXX_Size() int {
	return xxx_messageInfo_RequestLogMetaData.Size(m)
}
func (m *RequestLogMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLogMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLogMetaData proto.InternalMessageInfo

func (m *RequestLogMetaData) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *RequestLogMetaData) GetScopeName() string {
	if m != nil {
		return m.ScopeName
	}
	return ""
}

type NextBodyChunk struct {
	BodyChunk            []byte   `protobuf:"bytes,1,opt,name=bodyChunk,proto3" json:"bodyChunk,omitempty"`
	MoreBodyChunks       bool     `protobuf:"varint,2,opt,name=moreBodyChunks,proto3" json:"moreBodyChunks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextBodyChunk) Reset()         { *m = NextBodyChunk{} }
func (m *NextBodyChunk) String() string { return proto.CompactTextString(m) }
func (*NextBodyChunk) ProtoMessage()    {}
func (*NextBodyChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{4}
}
func (m *NextBodyChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextBodyChunk.Unmarshal(m, b)
}
func (m *NextBodyChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextBodyChunk.Marshal(b, m, deterministic)
}
func (dst *NextBodyChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextBodyChunk.Merge(dst, src)
}
func (m *NextBodyChunk) XXX_Size() int {
	return xxx_messageInfo_NextBodyChunk.Size(m)
}
func (m *NextBodyChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_NextBodyChunk.DiscardUnknown(m)
}

var xxx_messageInfo_NextBodyChunk proto.InternalMessageInfo

func (m *NextBodyChunk) GetBodyChunk() []byte {
	if m != nil {
		return m.BodyChunk
	}
	return nil
}

func (m *NextBodyChunk) GetMoreBodyChunks() bool {
	if m != nil {
		return m.MoreBodyChunks
	}
	return false
}

type WafDecision struct {
	Allow                bool     `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WafDecision) Reset()         { *m = WafDecision{} }
func (m *WafDecision) String() string { return proto.CompactTextString(m) }
func (*WafDecision) ProtoMessage()    {}
func (*WafDecision) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{5}
}
func (m *WafDecision) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WafDecision.Unmarshal(m, b)
}
func (m *WafDecision) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WafDecision.Marshal(b, m, deterministic)
}
func (dst *WafDecision) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WafDecision.Merge(dst, src)
}
func (m *WafDecision) XXX_Size() int {
	return xxx_messageInfo_WafDecision.Size(m)
}
func (m *WafDecision) XXX_DiscardUnknown() {
	xxx_messageInfo_WafDecision.DiscardUnknown(m)
}

var xxx_messageInfo_WafDecision proto.InternalMessageInfo

func (m *WafDecision) GetAllow() bool {
	if m != nil {
		return m.Allow
	}
	return false
}

type WAFConfig struct {
	ConfigVersion        int32              `protobuf:"varint,1,opt,name=configVersion,proto3" json:"configVersion,omitempty"`
	PolicyConfigs        []*PolicyConfig    `protobuf:"bytes,2,rep,name=policyConfigs,proto3" json:"policyConfigs,omitempty"`
	MetaData             *ConfigLogMetaData `protobuf:"bytes,3,opt,name=metaData,proto3" json:"metaData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WAFConfig) Reset()         { *m = WAFConfig{} }
func (m *WAFConfig) String() string { return proto.CompactTextString(m) }
func (*WAFConfig) ProtoMessage()    {}
func (*WAFConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{6}
}
func (m *WAFConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WAFConfig.Unmarshal(m, b)
}
func (m *WAFConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WAFConfig.Marshal(b, m, deterministic)
}
func (dst *WAFConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WAFConfig.Merge(dst, src)
}
func (m *WAFConfig) XXX_Size() int {
	return xxx_messageInfo_WAFConfig.Size(m)
}
func (m *WAFConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_WAFConfig.DiscardUnknown(m)
}

var xxx_messageInfo_WAFConfig proto.InternalMessageInfo

func (m *WAFConfig) GetConfigVersion() int32 {
	if m != nil {
		return m.ConfigVersion
	}
	return 0
}

func (m *WAFConfig) GetPolicyConfigs() []*PolicyConfig {
	if m != nil {
		return m.PolicyConfigs
	}
	return nil
}

func (m *WAFConfig) GetMetaData() *ConfigLogMetaData {
	if m != nil {
		return m.MetaData
	}
	return nil
}

type ConfigLogMetaData struct {
	ResourceID           string   `protobuf:"bytes,1,opt,name=resourceID,proto3" json:"resourceID,omitempty"`
	InstanceID           string   `protobuf:"bytes,2,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigLogMetaData) Reset()         { *m = ConfigLogMetaData{} }
func (m *ConfigLogMetaData) String() string { return proto.CompactTextString(m) }
func (*ConfigLogMetaData) ProtoMessage()    {}
func (*ConfigLogMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{7}
}
func (m *ConfigLogMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigLogMetaData.Unmarshal(m, b)
}
func (m *ConfigLogMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigLogMetaData.Marshal(b, m, deterministic)
}
func (dst *ConfigLogMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigLogMetaData.Merge(dst, src)
}
func (m *ConfigLogMetaData) XXX_Size() int {
	return xxx_messageInfo_ConfigLogMetaData.Size(m)
}
func (m *ConfigLogMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigLogMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigLogMetaData proto.InternalMessageInfo

func (m *ConfigLogMetaData) GetResourceID() string {
	if m != nil {
		return m.ResourceID
	}
	return ""
}

func (m *ConfigLogMetaData) GetInstanceID() string {
	if m != nil {
		return m.InstanceID
	}
	return ""
}

type CustomRule struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Priority             int32             `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	RuleType             string            `protobuf:"bytes,3,opt,name=ruleType,proto3" json:"ruleType,omitempty"`
	MatchConditions      []*MatchCondition `protobuf:"bytes,4,rep,name=matchConditions,proto3" json:"matchConditions,omitempty"`
	Action               string            `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CustomRule) Reset()         { *m = CustomRule{} }
func (m *CustomRule) String() string { return proto.CompactTextString(m) }
func (*CustomRule) ProtoMessage()    {}
func (*CustomRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{8}
}
func (m *CustomRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomRule.Unmarshal(m, b)
}
func (m *CustomRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomRule.Marshal(b, m, deterministic)
}
func (dst *CustomRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomRule.Merge(dst, src)
}
func (m *CustomRule) XXX_Size() int {
	return xxx_messageInfo_CustomRule.Size(m)
}
func (m *CustomRule) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomRule.DiscardUnknown(m)
}

var xxx_messageInfo_CustomRule proto.InternalMessageInfo

func (m *CustomRule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomRule) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *CustomRule) GetRuleType() string {
	if m != nil {
		return m.RuleType
	}
	return ""
}

func (m *CustomRule) GetMatchConditions() []*MatchCondition {
	if m != nil {
		return m.MatchConditions
	}
	return nil
}

func (m *CustomRule) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type MatchCondition struct {
	MatchVariables       []*MatchVariable `protobuf:"bytes,1,rep,name=matchVariables,proto3" json:"matchVariables,omitempty"`
	Operator             string           `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	NegateCondition      bool             `protobuf:"varint,3,opt,name=negateCondition,proto3" json:"negateCondition,omitempty"`
	MatchValues          []string         `protobuf:"bytes,4,rep,name=matchValues,proto3" json:"matchValues,omitempty"`
	Transforms           []string         `protobuf:"bytes,5,rep,name=transforms,proto3" json:"transforms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MatchCondition) Reset()         { *m = MatchCondition{} }
func (m *MatchCondition) String() string { return proto.CompactTextString(m) }
func (*MatchCondition) ProtoMessage()    {}
func (*MatchCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{9}
}
func (m *MatchCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchCondition.Unmarshal(m, b)
}
func (m *MatchCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchCondition.Marshal(b, m, deterministic)
}
func (dst *MatchCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchCondition.Merge(dst, src)
}
func (m *MatchCondition) XXX_Size() int {
	return xxx_messageInfo_MatchCondition.Size(m)
}
func (m *MatchCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchCondition.DiscardUnknown(m)
}

var xxx_messageInfo_MatchCondition proto.InternalMessageInfo

func (m *MatchCondition) GetMatchVariables() []*MatchVariable {
	if m != nil {
		return m.MatchVariables
	}
	return nil
}

func (m *MatchCondition) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MatchCondition) GetNegateCondition() bool {
	if m != nil {
		return m.NegateCondition
	}
	return false
}

func (m *MatchCondition) GetMatchValues() []string {
	if m != nil {
		return m.MatchValues
	}
	return nil
}

func (m *MatchCondition) GetTransforms() []string {
	if m != nil {
		return m.Transforms
	}
	return nil
}

type MatchVariable struct {
	VariableName         string   `protobuf:"bytes,1,opt,name=variableName,proto3" json:"variableName,omitempty"`
	Selector             string   `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchVariable) Reset()         { *m = MatchVariable{} }
func (m *MatchVariable) String() string { return proto.CompactTextString(m) }
func (*MatchVariable) ProtoMessage()    {}
func (*MatchVariable) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{10}
}
func (m *MatchVariable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchVariable.Unmarshal(m, b)
}
func (m *MatchVariable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchVariable.Marshal(b, m, deterministic)
}
func (dst *MatchVariable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchVariable.Merge(dst, src)
}
func (m *MatchVariable) XXX_Size() int {
	return xxx_messageInfo_MatchVariable.Size(m)
}
func (m *MatchVariable) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchVariable.DiscardUnknown(m)
}

var xxx_messageInfo_MatchVariable proto.InternalMessageInfo

func (m *MatchVariable) GetVariableName() string {
	if m != nil {
		return m.VariableName
	}
	return ""
}

func (m *MatchVariable) GetSelector() string {
	if m != nil {
		return m.Selector
	}
	return ""
}

type PolicyConfig struct {
	ConfigID             string              `protobuf:"bytes,1,opt,name=configID,proto3" json:"configID,omitempty"`
	SecRuleConfig        *SecRuleConfig      `protobuf:"bytes,2,opt,name=secRuleConfig,proto3" json:"secRuleConfig,omitempty"`
	CustomRuleConfig     *CustomRuleConfig   `protobuf:"bytes,3,opt,name=customRuleConfig,proto3" json:"customRuleConfig,omitempty"`
	IpReputationConfig   *IPReputationConfig `protobuf:"bytes,4,opt,name=ipReputationConfig,proto3" json:"ipReputationConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PolicyConfig) Reset()         { *m = PolicyConfig{} }
func (m *PolicyConfig) String() string { return proto.CompactTextString(m) }
func (*PolicyConfig) ProtoMessage()    {}
func (*PolicyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{11}
}
func (m *PolicyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyConfig.Unmarshal(m, b)
}
func (m *PolicyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyConfig.Marshal(b, m, deterministic)
}
func (dst *PolicyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyConfig.Merge(dst, src)
}
func (m *PolicyConfig) XXX_Size() int {
	return xxx_messageInfo_PolicyConfig.Size(m)
}
func (m *PolicyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyConfig proto.InternalMessageInfo

func (m *PolicyConfig) GetConfigID() string {
	if m != nil {
		return m.ConfigID
	}
	return ""
}

func (m *PolicyConfig) GetSecRuleConfig() *SecRuleConfig {
	if m != nil {
		return m.SecRuleConfig
	}
	return nil
}

func (m *PolicyConfig) GetCustomRuleConfig() *CustomRuleConfig {
	if m != nil {
		return m.CustomRuleConfig
	}
	return nil
}

func (m *PolicyConfig) GetIpReputationConfig() *IPReputationConfig {
	if m != nil {
		return m.IpReputationConfig
	}
	return nil
}

type SecRuleConfig struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RuleSetId            string   `protobuf:"bytes,2,opt,name=ruleSetId,proto3" json:"ruleSetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecRuleConfig) Reset()         { *m = SecRuleConfig{} }
func (m *SecRuleConfig) String() string { return proto.CompactTextString(m) }
func (*SecRuleConfig) ProtoMessage()    {}
func (*SecRuleConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{12}
}
func (m *SecRuleConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecRuleConfig.Unmarshal(m, b)
}
func (m *SecRuleConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecRuleConfig.Marshal(b, m, deterministic)
}
func (dst *SecRuleConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecRuleConfig.Merge(dst, src)
}
func (m *SecRuleConfig) XXX_Size() int {
	return xxx_messageInfo_SecRuleConfig.Size(m)
}
func (m *SecRuleConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SecRuleConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SecRuleConfig proto.InternalMessageInfo

func (m *SecRuleConfig) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *SecRuleConfig) GetRuleSetId() string {
	if m != nil {
		return m.RuleSetId
	}
	return ""
}

type CustomRuleConfig struct {
	CustomRules          []*CustomRule `protobuf:"bytes,1,rep,name=customRules,proto3" json:"customRules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CustomRuleConfig) Reset()         { *m = CustomRuleConfig{} }
func (m *CustomRuleConfig) String() string { return proto.CompactTextString(m) }
func (*CustomRuleConfig) ProtoMessage()    {}
func (*CustomRuleConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{13}
}
func (m *CustomRuleConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomRuleConfig.Unmarshal(m, b)
}
func (m *CustomRuleConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomRuleConfig.Marshal(b, m, deterministic)
}
func (dst *CustomRuleConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomRuleConfig.Merge(dst, src)
}
func (m *CustomRuleConfig) XXX_Size() int {
	return xxx_messageInfo_CustomRuleConfig.Size(m)
}
func (m *CustomRuleConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomRuleConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CustomRuleConfig proto.InternalMessageInfo

func (m *CustomRuleConfig) GetCustomRules() []*CustomRule {
	if m != nil {
		return m.CustomRules
	}
	return nil
}

type IPReputationConfig struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPReputationConfig) Reset()         { *m = IPReputationConfig{} }
func (m *IPReputationConfig) String() string { return proto.CompactTextString(m) }
func (*IPReputationConfig) ProtoMessage()    {}
func (*IPReputationConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{14}
}
func (m *IPReputationConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPReputationConfig.Unmarshal(m, b)
}
func (m *IPReputationConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPReputationConfig.Marshal(b, m, deterministic)
}
func (dst *IPReputationConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPReputationConfig.Merge(dst, src)
}
func (m *IPReputationConfig) XXX_Size() int {
	return xxx_messageInfo_IPReputationConfig.Size(m)
}
func (m *IPReputationConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IPReputationConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IPReputationConfig proto.InternalMessageInfo

func (m *IPReputationConfig) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type PutConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutConfigResponse) Reset()         { *m = PutConfigResponse{} }
func (m *PutConfigResponse) String() string { return proto.CompactTextString(m) }
func (*PutConfigResponse) ProtoMessage()    {}
func (*PutConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{15}
}
func (m *PutConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutConfigResponse.Unmarshal(m, b)
}
func (m *PutConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutConfigResponse.Marshal(b, m, deterministic)
}
func (dst *PutConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutConfigResponse.Merge(dst, src)
}
func (m *PutConfigResponse) XXX_Size() int {
	return xxx_messageInfo_PutConfigResponse.Size(m)
}
func (m *PutConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutConfigResponse proto.InternalMessageInfo

type WAFConfigVersion struct {
	ConfigVersion        int32    `protobuf:"varint,1,opt,name=configVersion,proto3" json:"configVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WAFConfigVersion) Reset()         { *m = WAFConfigVersion{} }
func (m *WAFConfigVersion) String() string { return proto.CompactTextString(m) }
func (*WAFConfigVersion) ProtoMessage()    {}
func (*WAFConfigVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{16}
}
func (m *WAFConfigVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WAFConfigVersion.Unmarshal(m, b)
}
func (m *WAFConfigVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WAFConfigVersion.Marshal(b, m, deterministic)
}
func (dst *WAFConfigVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WAFConfigVersion.Merge(dst, src)
}
func (m *WAFConfigVersion) XXX_Size() int {
	return xxx_messageInfo_WAFConfigVersion.Size(m)
}
func (m *WAFConfigVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_WAFConfigVersion.DiscardUnknown(m)
}

var xxx_messageInfo_WAFConfigVersion proto.InternalMessageInfo

func (m *WAFConfigVersion) GetConfigVersion() int32 {
	if m != nil {
		return m.ConfigVersion
	}
	return 0
}

type DisposeConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisposeConfigResponse) Reset()         { *m = DisposeConfigResponse{} }
func (m *DisposeConfigResponse) String() string { return proto.CompactTextString(m) }
func (*DisposeConfigResponse) ProtoMessage()    {}
func (*DisposeConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_423cb6574206dc0c, []int{17}
}
func (m *DisposeConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisposeConfigResponse.Unmarshal(m, b)
}
func (m *DisposeConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisposeConfigResponse.Marshal(b, m, deterministic)
}
func (dst *DisposeConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisposeConfigResponse.Merge(dst, src)
}
func (m *DisposeConfigResponse) XXX_Size() int {
	return xxx_messageInfo_DisposeConfigResponse.Size(m)
}
func (m *DisposeConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisposeConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisposeConfigResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HeaderPair)(nil), "wafservice.HeaderPair")
	proto.RegisterType((*WafHttpRequest)(nil), "wafservice.WafHttpRequest")
	proto.RegisterType((*HeadersAndFirstChunk)(nil), "wafservice.HeadersAndFirstChunk")
	proto.RegisterType((*RequestLogMetaData)(nil), "wafservice.RequestLogMetaData")
	proto.RegisterType((*NextBodyChunk)(nil), "wafservice.NextBodyChunk")
	proto.RegisterType((*WafDecision)(nil), "wafservice.WafDecision")
	proto.RegisterType((*WAFConfig)(nil), "wafservice.WAFConfig")
	proto.RegisterType((*ConfigLogMetaData)(nil), "wafservice.ConfigLogMetaData")
	proto.RegisterType((*CustomRule)(nil), "wafservice.CustomRule")
	proto.RegisterType((*MatchCondition)(nil), "wafservice.MatchCondition")
	proto.RegisterType((*MatchVariable)(nil), "wafservice.MatchVariable")
	proto.RegisterType((*PolicyConfig)(nil), "wafservice.PolicyConfig")
	proto.RegisterType((*SecRuleConfig)(nil), "wafservice.SecRuleConfig")
	proto.RegisterType((*CustomRuleConfig)(nil), "wafservice.CustomRuleConfig")
	proto.RegisterType((*IPReputationConfig)(nil), "wafservice.IPReputationConfig")
	proto.RegisterType((*PutConfigResponse)(nil), "wafservice.PutConfigResponse")
	proto.RegisterType((*WAFConfigVersion)(nil), "wafservice.WAFConfigVersion")
	proto.RegisterType((*DisposeConfigResponse)(nil), "wafservice.DisposeConfigResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WafServiceClient is the client API for WafService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WafServiceClient interface {
	EvalRequest(ctx context.Context, opts ...grpc.CallOption) (WafService_EvalRequestClient, error)
	PutConfig(ctx context.Context, in *WAFConfig, opts ...grpc.CallOption) (*PutConfigResponse, error)
	DisposeConfig(ctx context.Context, in *WAFConfigVersion, opts ...grpc.CallOption) (*DisposeConfigResponse, error)
}

type wafServiceClient struct {
	cc *grpc.ClientConn
}

func NewWafServiceClient(cc *grpc.ClientConn) WafServiceClient {
	return &wafServiceClient{cc}
}

func (c *wafServiceClient) EvalRequest(ctx context.Context, opts ...grpc.CallOption) (WafService_EvalRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WafService_serviceDesc.Streams[0], "/wafservice.WafService/EvalRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &wafServiceEvalRequestClient{stream}
	return x, nil
}

type WafService_EvalRequestClient interface {
	Send(*WafHttpRequest) error
	CloseAndRecv() (*WafDecision, error)
	grpc.ClientStream
}

type wafServiceEvalRequestClient struct {
	grpc.ClientStream
}

func (x *wafServiceEvalRequestClient) Send(m *WafHttpRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *wafServiceEvalRequestClient) CloseAndRecv() (*WafDecision, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WafDecision)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wafServiceClient) PutConfig(ctx context.Context, in *WAFConfig, opts ...grpc.CallOption) (*PutConfigResponse, error) {
	out := new(PutConfigResponse)
	err := c.cc.Invoke(ctx, "/wafservice.WafService/PutConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) DisposeConfig(ctx context.Context, in *WAFConfigVersion, opts ...grpc.CallOption) (*DisposeConfigResponse, error) {
	out := new(DisposeConfigResponse)
	err := c.cc.Invoke(ctx, "/wafservice.WafService/DisposeConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WafServiceServer is the server API for WafService service.
type WafServiceServer interface {
	EvalRequest(WafService_EvalRequestServer) error
	PutConfig(context.Context, *WAFConfig) (*PutConfigResponse, error)
	DisposeConfig(context.Context, *WAFConfigVersion) (*DisposeConfigResponse, error)
}

func RegisterWafServiceServer(s *grpc.Server, srv WafServiceServer) {
	s.RegisterService(&_WafService_serviceDesc, srv)
}

func _WafService_EvalRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WafServiceServer).EvalRequest(&wafServiceEvalRequestServer{stream})
}

type WafService_EvalRequestServer interface {
	SendAndClose(*WafDecision) error
	Recv() (*WafHttpRequest, error)
	grpc.ServerStream
}

type wafServiceEvalRequestServer struct {
	grpc.ServerStream
}

func (x *wafServiceEvalRequestServer) SendAndClose(m *WafDecision) error {
	return x.ServerStream.SendMsg(m)
}

func (x *wafServiceEvalRequestServer) Recv() (*WafHttpRequest, error) {
	m := new(WafHttpRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _WafService_PutConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WAFConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).PutConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wafservice.WafService/PutConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).PutConfig(ctx, req.(*WAFConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_DisposeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WAFConfigVersion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).DisposeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wafservice.WafService/DisposeConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).DisposeConfig(ctx, req.(*WAFConfigVersion))
	}
	return interceptor(ctx, in, info, handler)
}

var _WafService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wafservice.WafService",
	HandlerType: (*WafServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutConfig",
			Handler:    _WafService_PutConfig_Handler,
		},
		{
			MethodName: "DisposeConfig",
			Handler:    _WafService_DisposeConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EvalRequest",
			Handler:       _WafService_EvalRequest_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "waf.proto",
}

func init() { proto.RegisterFile("waf.proto", fileDescriptor_waf_423cb6574206dc0c) }

var fileDescriptor_waf_423cb6574206dc0c = []byte{
	// 924 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xcd, 0x72, 0xe3, 0x44,
	0x10, 0xb6, 0x9c, 0x64, 0x63, 0xb5, 0xe3, 0x6c, 0x76, 0xc8, 0x66, 0xb5, 0xae, 0xb0, 0x65, 0x06,
	0x8a, 0xf2, 0x29, 0x45, 0x05, 0x0e, 0x0b, 0x07, 0x28, 0xaf, 0x4d, 0x70, 0xaa, 0x76, 0x43, 0x6a,
	0x02, 0xc9, 0x79, 0x22, 0xb5, 0x13, 0x55, 0x64, 0x8d, 0x98, 0x19, 0x25, 0xf8, 0x01, 0x78, 0x1b,
	0xce, 0x1c, 0x78, 0x15, 0x9e, 0x81, 0x77, 0xa0, 0x66, 0xf4, 0x63, 0x49, 0x16, 0x55, 0x7b, 0x9b,
	0xee, 0xf9, 0xba, 0xe7, 0xfb, 0xba, 0x5b, 0x6d, 0x83, 0xfb, 0xc4, 0x17, 0x27, 0x89, 0x14, 0x5a,
	0x10, 0x78, 0xe2, 0x0b, 0x85, 0xf2, 0x31, 0xf4, 0x91, 0x7e, 0x03, 0x30, 0x47, 0x1e, 0xa0, 0xbc,
	0xe4, 0xa1, 0x24, 0x07, 0xb0, 0xf5, 0x80, 0x2b, 0xcf, 0x19, 0x39, 0x63, 0x97, 0x99, 0x23, 0x39,
	0x84, 0x9d, 0x47, 0x1e, 0xa5, 0xe8, 0x75, 0xad, 0x2f, 0x33, 0xe8, 0x5f, 0x0e, 0xec, 0xdf, 0xf0,
	0xc5, 0x5c, 0xeb, 0x84, 0xe1, 0x6f, 0x29, 0x2a, 0x4d, 0xae, 0xe1, 0xf0, 0xde, 0x26, 0x52, 0x93,
	0x38, 0x38, 0x0b, 0xa5, 0xd2, 0xd3, 0xfb, 0x34, 0x7e, 0xb0, 0xb9, 0xfa, 0xa7, 0xa3, 0x93, 0xf5,
	0x9b, 0x27, 0xf3, 0x16, 0xdc, 0xbc, 0xc3, 0x5a, 0xe3, 0xc9, 0x04, 0x06, 0x31, 0xfe, 0xae, 0xdf,
	0x89, 0x60, 0x95, 0x25, 0xec, 0xda, 0x84, 0xaf, 0xab, 0x09, 0x2f, 0xaa, 0x80, 0x79, 0x87, 0xd5,
	0x23, 0xde, 0xb9, 0xb0, 0xeb, 0x8b, 0x58, 0x63, 0xac, 0xe9, 0xdf, 0x5d, 0x38, 0x6c, 0x7b, 0x9e,
	0xbc, 0x01, 0x90, 0xb8, 0x14, 0x1a, 0x27, 0x41, 0x20, 0x3d, 0xd7, 0x8a, 0xad, 0x78, 0xc8, 0x10,
	0x7a, 0xbe, 0x88, 0x17, 0xe1, 0xdd, 0xf9, 0xcc, 0xdb, 0xb5, 0xb7, 0xa5, 0x4d, 0xbe, 0x83, 0xde,
	0x12, 0x35, 0x9f, 0x71, 0xcd, 0xbd, 0x9e, 0x65, 0xf7, 0xa6, 0xca, 0x2e, 0xaf, 0xd0, 0x7b, 0x71,
	0xf7, 0x21, 0x47, 0xb1, 0x12, 0x4f, 0x8e, 0xe0, 0xd9, 0x12, 0xf5, 0xbd, 0x08, 0xf2, 0xa2, 0xe7,
	0x96, 0xe9, 0x44, 0x2a, 0xc3, 0xbc, 0xea, 0xe6, 0x48, 0xbe, 0x82, 0xdd, 0xbc, 0x40, 0xde, 0xd6,
	0x68, 0x6b, 0xdc, 0x3f, 0x3d, 0xda, 0xac, 0xa9, 0x69, 0x22, 0x2b, 0x60, 0xe4, 0x4b, 0xd8, 0x5f,
	0x18, 0x85, 0xeb, 0xda, 0x6d, 0x8f, 0x9c, 0xf1, 0x1e, 0x6b, 0x78, 0x0d, 0x6e, 0x29, 0x24, 0x96,
	0x0e, 0xe5, 0xed, 0x8c, 0x9c, 0x71, 0x8f, 0x35, 0xbc, 0x74, 0x0e, 0x64, 0x53, 0x8b, 0x99, 0x10,
	0xe5, 0x8b, 0x04, 0x73, 0x01, 0x99, 0x41, 0x8e, 0xc1, 0xb5, 0x87, 0x0b, 0xbe, 0x2c, 0x66, 0x67,
	0xed, 0xa0, 0xbf, 0xc2, 0xa0, 0xd6, 0x33, 0x03, 0xbf, 0x2d, 0x59, 0x3a, 0x96, 0xe5, 0xda, 0xd1,
	0x42, 0xb0, 0xdb, 0x4a, 0xf0, 0x73, 0xe8, 0xdf, 0xf0, 0xc5, 0x0c, 0xfd, 0x50, 0x85, 0x22, 0x36,
	0xcc, 0x78, 0x14, 0x89, 0x27, 0x9b, 0xb0, 0xc7, 0x32, 0x83, 0xfe, 0xe9, 0x80, 0x7b, 0x33, 0x39,
	0x9b, 0xda, 0xee, 0x91, 0x2f, 0x60, 0x90, 0xf5, 0xf1, 0x1a, 0xa5, 0x09, 0xb2, 0xd8, 0x1d, 0x56,
	0x77, 0x92, 0xef, 0x61, 0x90, 0x88, 0x28, 0xf4, 0x57, 0x59, 0x94, 0x79, 0xdf, 0x74, 0xc0, 0xab,
	0x76, 0xe0, 0xb2, 0x02, 0x60, 0x75, 0x38, 0xf9, 0xb6, 0x32, 0x21, 0x5b, 0x76, 0x42, 0x3e, 0xad,
	0x86, 0x66, 0xb0, 0xd6, 0x01, 0xa1, 0x57, 0xf0, 0x62, 0xe3, 0x3a, 0x9b, 0x56, 0x25, 0x52, 0xe9,
	0xe3, 0xf9, 0x2c, 0x2f, 0x7c, 0xc5, 0x63, 0xee, 0xc3, 0x58, 0x69, 0x1e, 0xdb, 0xfb, 0xac, 0xfc,
	0x15, 0x8f, 0xf9, 0x7e, 0x61, 0x9a, 0x2a, 0x2d, 0x96, 0x2c, 0x8d, 0x90, 0x10, 0xd8, 0x8e, 0x4d,
	0x9f, 0xb2, 0x44, 0xf6, 0x6c, 0x06, 0x3e, 0x91, 0xa1, 0x90, 0xa1, 0x5e, 0xd9, 0x04, 0x3b, 0xac,
	0xb4, 0xcd, 0x9d, 0x4c, 0x23, 0xfc, 0x65, 0x95, 0xa0, 0x95, 0xe3, 0xb2, 0xd2, 0x26, 0x33, 0x78,
	0xbe, 0xe4, 0xda, 0xbf, 0x9f, 0x8a, 0x38, 0x08, 0x75, 0x28, 0x62, 0xe5, 0x6d, 0xdb, 0x62, 0x0d,
	0xab, 0x8a, 0x3f, 0xd4, 0x20, 0xac, 0x19, 0x62, 0x3e, 0x0b, 0xee, 0x9b, 0xa3, 0x1d, 0x45, 0x97,
	0xe5, 0x16, 0xfd, 0xc7, 0x81, 0xfd, 0x7a, 0x2c, 0x99, 0xc0, 0xbe, 0x8d, 0xbe, 0xe6, 0x32, 0xe4,
	0xb7, 0x11, 0x2a, 0xcf, 0xb1, 0xef, 0xbd, 0xde, 0x78, 0xaf, 0x40, 0xb0, 0x46, 0x80, 0xd1, 0x23,
	0x12, 0x94, 0x5c, 0x0b, 0x99, 0x17, 0xab, 0xb4, 0xc9, 0x18, 0x9e, 0xc7, 0x78, 0xc7, 0x35, 0x96,
	0x2f, 0x5a, 0xc9, 0x3d, 0xd6, 0x74, 0x93, 0x11, 0xf4, 0xf3, 0xbc, 0x51, 0x8a, 0x99, 0x6a, 0x97,
	0x55, 0x5d, 0xa6, 0x2d, 0x5a, 0xf2, 0x58, 0x2d, 0x84, 0x5c, 0x9a, 0x8f, 0xcc, 0x00, 0x2a, 0x1e,
	0xfa, 0x33, 0x0c, 0x6a, 0x44, 0x09, 0x85, 0xbd, 0xc7, 0xfc, 0x7c, 0xb1, 0x6e, 0x50, 0xcd, 0x67,
	0xc8, 0x2b, 0x8c, 0xd0, 0xaf, 0x90, 0x2f, 0x6c, 0xfa, 0x47, 0x17, 0xf6, 0xaa, 0x73, 0x59, 0x5b,
	0x63, 0x4e, 0x63, 0x8d, 0xfd, 0x00, 0x03, 0x85, 0xbe, 0x19, 0x88, 0x0c, 0xdc, 0xb6, 0x69, 0xaf,
	0xaa, 0x00, 0x56, 0xc7, 0x93, 0x39, 0x1c, 0xf8, 0xe5, 0x50, 0xe5, 0x39, 0xb2, 0x69, 0x3f, 0xae,
	0x4d, 0x7b, 0x03, 0xc3, 0x36, 0xa2, 0xc8, 0x05, 0x90, 0x30, 0x61, 0x98, 0xa4, 0x9a, 0x9b, 0xd2,
	0xe6, 0xb9, 0xb6, 0x37, 0x77, 0xeb, 0xf9, 0x65, 0x13, 0xc5, 0x5a, 0x22, 0xe9, 0x4f, 0x30, 0xa8,
	0x31, 0x27, 0x1e, 0xec, 0x62, 0x6c, 0x4a, 0x18, 0xe4, 0xcb, 0xa1, 0x30, 0xcd, 0x26, 0x32, 0xb3,
	0x7c, 0x85, 0xfa, 0x3c, 0x28, 0x16, 0x57, 0xe9, 0xa0, 0xef, 0xe1, 0xa0, 0x49, 0x9f, 0xbc, 0x85,
	0xfe, 0x5a, 0x40, 0x31, 0x7d, 0x47, 0xed, 0x8a, 0x59, 0x15, 0x4a, 0x4f, 0x80, 0x6c, 0x0a, 0xf8,
	0x7f, 0x6e, 0xf4, 0x13, 0x78, 0x71, 0x99, 0xea, 0x5c, 0x27, 0xaa, 0x44, 0xc4, 0x0a, 0xe9, 0x5b,
	0x38, 0x28, 0xd7, 0x59, 0xb1, 0xaf, 0x3e, 0x6a, 0xab, 0xd1, 0x57, 0xf0, 0x72, 0x16, 0xaa, 0x44,
	0x28, 0xac, 0xa7, 0x3c, 0xfd, 0xd7, 0x01, 0xb8, 0xe1, 0x8b, 0xab, 0x8c, 0x3e, 0x39, 0x83, 0xfe,
	0x8f, 0x8f, 0x3c, 0x2a, 0x7e, 0xe9, 0x6b, 0x1f, 0x72, 0xfd, 0x5f, 0xc0, 0xf0, 0x55, 0xe3, 0xae,
	0xd8, 0xc5, 0xb4, 0x33, 0x76, 0xc8, 0x14, 0xdc, 0x92, 0x3e, 0x79, 0x59, 0x43, 0x16, 0x02, 0x86,
	0xb5, 0xbd, 0xb8, 0x29, 0xb6, 0x43, 0x18, 0x0c, 0x6a, 0xa4, 0xc9, 0x71, 0x6b, 0xa2, 0x5c, 0xe3,
	0xf0, 0xb3, 0xea, 0x6d, 0xab, 0x5a, 0xda, 0xb9, 0x7d, 0x66, 0xff, 0x17, 0x7d, 0xfd, 0x5f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb8, 0xb0, 0x14, 0x3a, 0x24, 0x09, 0x00, 0x00,
}
