// Code generated by protoc-gen-go. DO NOT EDIT.
// source: waf.proto

package wafservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HeaderPair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeaderPair) Reset()         { *m = HeaderPair{} }
func (m *HeaderPair) String() string { return proto.CompactTextString(m) }
func (*HeaderPair) ProtoMessage()    {}
func (*HeaderPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_dbcbac74d78700a8, []int{0}
}
func (m *HeaderPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderPair.Unmarshal(m, b)
}
func (m *HeaderPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderPair.Marshal(b, m, deterministic)
}
func (dst *HeaderPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderPair.Merge(dst, src)
}
func (m *HeaderPair) XXX_Size() int {
	return xxx_messageInfo_HeaderPair.Size(m)
}
func (m *HeaderPair) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderPair.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderPair proto.InternalMessageInfo

func (m *HeaderPair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HeaderPair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type WafHttpRequest struct {
	Method  string        `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Uri     string        `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Headers []*HeaderPair `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	// TODO Use gRPC streaming instead of a simple string type
	Body                 []byte   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WafHttpRequest) Reset()         { *m = WafHttpRequest{} }
func (m *WafHttpRequest) String() string { return proto.CompactTextString(m) }
func (*WafHttpRequest) ProtoMessage()    {}
func (*WafHttpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_dbcbac74d78700a8, []int{1}
}
func (m *WafHttpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WafHttpRequest.Unmarshal(m, b)
}
func (m *WafHttpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WafHttpRequest.Marshal(b, m, deterministic)
}
func (dst *WafHttpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WafHttpRequest.Merge(dst, src)
}
func (m *WafHttpRequest) XXX_Size() int {
	return xxx_messageInfo_WafHttpRequest.Size(m)
}
func (m *WafHttpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WafHttpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WafHttpRequest proto.InternalMessageInfo

func (m *WafHttpRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *WafHttpRequest) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *WafHttpRequest) GetHeaders() []*HeaderPair {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *WafHttpRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type WafDecision struct {
	Allow                bool     `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WafDecision) Reset()         { *m = WafDecision{} }
func (m *WafDecision) String() string { return proto.CompactTextString(m) }
func (*WafDecision) ProtoMessage()    {}
func (*WafDecision) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_dbcbac74d78700a8, []int{2}
}
func (m *WafDecision) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WafDecision.Unmarshal(m, b)
}
func (m *WafDecision) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WafDecision.Marshal(b, m, deterministic)
}
func (dst *WafDecision) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WafDecision.Merge(dst, src)
}
func (m *WafDecision) XXX_Size() int {
	return xxx_messageInfo_WafDecision.Size(m)
}
func (m *WafDecision) XXX_DiscardUnknown() {
	xxx_messageInfo_WafDecision.DiscardUnknown(m)
}

var xxx_messageInfo_WafDecision proto.InternalMessageInfo

func (m *WafDecision) GetAllow() bool {
	if m != nil {
		return m.Allow
	}
	return false
}

type WAFConfig struct {
	SecRuleConfigs       []*SecRuleConfig      `protobuf:"bytes,1,rep,name=secRuleConfigs,proto3" json:"secRuleConfigs,omitempty"`
	GeoDBConfigs         []*GeoDBConfig        `protobuf:"bytes,2,rep,name=geoDBConfigs,proto3" json:"geoDBConfigs,omitempty"`
	IpReputationConfigs  []*IPReputationConfig `protobuf:"bytes,3,rep,name=ipReputationConfigs,proto3" json:"ipReputationConfigs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *WAFConfig) Reset()         { *m = WAFConfig{} }
func (m *WAFConfig) String() string { return proto.CompactTextString(m) }
func (*WAFConfig) ProtoMessage()    {}
func (*WAFConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_dbcbac74d78700a8, []int{3}
}
func (m *WAFConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WAFConfig.Unmarshal(m, b)
}
func (m *WAFConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WAFConfig.Marshal(b, m, deterministic)
}
func (dst *WAFConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WAFConfig.Merge(dst, src)
}
func (m *WAFConfig) XXX_Size() int {
	return xxx_messageInfo_WAFConfig.Size(m)
}
func (m *WAFConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_WAFConfig.DiscardUnknown(m)
}

var xxx_messageInfo_WAFConfig proto.InternalMessageInfo

func (m *WAFConfig) GetSecRuleConfigs() []*SecRuleConfig {
	if m != nil {
		return m.SecRuleConfigs
	}
	return nil
}

func (m *WAFConfig) GetGeoDBConfigs() []*GeoDBConfig {
	if m != nil {
		return m.GeoDBConfigs
	}
	return nil
}

func (m *WAFConfig) GetIpReputationConfigs() []*IPReputationConfig {
	if m != nil {
		return m.IpReputationConfigs
	}
	return nil
}

type SecRuleConfig struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled              bool     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecRuleConfig) Reset()         { *m = SecRuleConfig{} }
func (m *SecRuleConfig) String() string { return proto.CompactTextString(m) }
func (*SecRuleConfig) ProtoMessage()    {}
func (*SecRuleConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_dbcbac74d78700a8, []int{4}
}
func (m *SecRuleConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecRuleConfig.Unmarshal(m, b)
}
func (m *SecRuleConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecRuleConfig.Marshal(b, m, deterministic)
}
func (dst *SecRuleConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecRuleConfig.Merge(dst, src)
}
func (m *SecRuleConfig) XXX_Size() int {
	return xxx_messageInfo_SecRuleConfig.Size(m)
}
func (m *SecRuleConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SecRuleConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SecRuleConfig proto.InternalMessageInfo

func (m *SecRuleConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SecRuleConfig) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type GeoDBConfig struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled              bool     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeoDBConfig) Reset()         { *m = GeoDBConfig{} }
func (m *GeoDBConfig) String() string { return proto.CompactTextString(m) }
func (*GeoDBConfig) ProtoMessage()    {}
func (*GeoDBConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_dbcbac74d78700a8, []int{5}
}
func (m *GeoDBConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoDBConfig.Unmarshal(m, b)
}
func (m *GeoDBConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoDBConfig.Marshal(b, m, deterministic)
}
func (dst *GeoDBConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoDBConfig.Merge(dst, src)
}
func (m *GeoDBConfig) XXX_Size() int {
	return xxx_messageInfo_GeoDBConfig.Size(m)
}
func (m *GeoDBConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoDBConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GeoDBConfig proto.InternalMessageInfo

func (m *GeoDBConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GeoDBConfig) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type IPReputationConfig struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled              bool     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPReputationConfig) Reset()         { *m = IPReputationConfig{} }
func (m *IPReputationConfig) String() string { return proto.CompactTextString(m) }
func (*IPReputationConfig) ProtoMessage()    {}
func (*IPReputationConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_dbcbac74d78700a8, []int{6}
}
func (m *IPReputationConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPReputationConfig.Unmarshal(m, b)
}
func (m *IPReputationConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPReputationConfig.Marshal(b, m, deterministic)
}
func (dst *IPReputationConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPReputationConfig.Merge(dst, src)
}
func (m *IPReputationConfig) XXX_Size() int {
	return xxx_messageInfo_IPReputationConfig.Size(m)
}
func (m *IPReputationConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IPReputationConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IPReputationConfig proto.InternalMessageInfo

func (m *IPReputationConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IPReputationConfig) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type PutConfigResponse struct {
	Version              int64    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutConfigResponse) Reset()         { *m = PutConfigResponse{} }
func (m *PutConfigResponse) String() string { return proto.CompactTextString(m) }
func (*PutConfigResponse) ProtoMessage()    {}
func (*PutConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_waf_dbcbac74d78700a8, []int{7}
}
func (m *PutConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutConfigResponse.Unmarshal(m, b)
}
func (m *PutConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutConfigResponse.Marshal(b, m, deterministic)
}
func (dst *PutConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutConfigResponse.Merge(dst, src)
}
func (m *PutConfigResponse) XXX_Size() int {
	return xxx_messageInfo_PutConfigResponse.Size(m)
}
func (m *PutConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutConfigResponse proto.InternalMessageInfo

func (m *PutConfigResponse) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*HeaderPair)(nil), "wafservice.HeaderPair")
	proto.RegisterType((*WafHttpRequest)(nil), "wafservice.WafHttpRequest")
	proto.RegisterType((*WafDecision)(nil), "wafservice.WafDecision")
	proto.RegisterType((*WAFConfig)(nil), "wafservice.WAFConfig")
	proto.RegisterType((*SecRuleConfig)(nil), "wafservice.SecRuleConfig")
	proto.RegisterType((*GeoDBConfig)(nil), "wafservice.GeoDBConfig")
	proto.RegisterType((*IPReputationConfig)(nil), "wafservice.IPReputationConfig")
	proto.RegisterType((*PutConfigResponse)(nil), "wafservice.PutConfigResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WafServiceClient is the client API for WafService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WafServiceClient interface {
	EvalRequest(ctx context.Context, in *WafHttpRequest, opts ...grpc.CallOption) (*WafDecision, error)
	PutConfig(ctx context.Context, in *WAFConfig, opts ...grpc.CallOption) (*PutConfigResponse, error)
}

type wafServiceClient struct {
	cc *grpc.ClientConn
}

func NewWafServiceClient(cc *grpc.ClientConn) WafServiceClient {
	return &wafServiceClient{cc}
}

func (c *wafServiceClient) EvalRequest(ctx context.Context, in *WafHttpRequest, opts ...grpc.CallOption) (*WafDecision, error) {
	out := new(WafDecision)
	err := c.cc.Invoke(ctx, "/wafservice.WafService/EvalRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) PutConfig(ctx context.Context, in *WAFConfig, opts ...grpc.CallOption) (*PutConfigResponse, error) {
	out := new(PutConfigResponse)
	err := c.cc.Invoke(ctx, "/wafservice.WafService/PutConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WafServiceServer is the server API for WafService service.
type WafServiceServer interface {
	EvalRequest(context.Context, *WafHttpRequest) (*WafDecision, error)
	PutConfig(context.Context, *WAFConfig) (*PutConfigResponse, error)
}

func RegisterWafServiceServer(s *grpc.Server, srv WafServiceServer) {
	s.RegisterService(&_WafService_serviceDesc, srv)
}

func _WafService_EvalRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WafHttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).EvalRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wafservice.WafService/EvalRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).EvalRequest(ctx, req.(*WafHttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_PutConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WAFConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).PutConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wafservice.WafService/PutConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).PutConfig(ctx, req.(*WAFConfig))
	}
	return interceptor(ctx, in, info, handler)
}

var _WafService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wafservice.WafService",
	HandlerType: (*WafServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvalRequest",
			Handler:    _WafService_EvalRequest_Handler,
		},
		{
			MethodName: "PutConfig",
			Handler:    _WafService_PutConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "waf.proto",
}

func init() { proto.RegisterFile("waf.proto", fileDescriptor_waf_dbcbac74d78700a8) }

var fileDescriptor_waf_dbcbac74d78700a8 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x93, 0xd2, 0x36, 0xe3, 0x12, 0xc1, 0x00, 0xad, 0x89, 0x04, 0x8a, 0x96, 0x4b, 0x2e,
	0x44, 0xa8, 0x20, 0x21, 0x84, 0x84, 0x54, 0x1a, 0xa0, 0xdc, 0xac, 0xed, 0xc1, 0xe7, 0x4d, 0x3c,
	0x6e, 0x57, 0x18, 0xaf, 0xf1, 0xae, 0x1d, 0xf5, 0xc6, 0x5f, 0xf0, 0x75, 0xfc, 0x0b, 0xf2, 0xda,
	0x4b, 0xec, 0xb4, 0x97, 0xdc, 0x66, 0x66, 0xdf, 0x7b, 0xf3, 0x3c, 0x33, 0x86, 0xd1, 0x5a, 0x24,
	0xf3, 0xbc, 0x50, 0x46, 0x21, 0xac, 0x45, 0xa2, 0xa9, 0xa8, 0xe4, 0x8a, 0xd8, 0x3b, 0x80, 0x4b,
	0x12, 0x31, 0x15, 0xa1, 0x90, 0x05, 0x3e, 0x82, 0xe1, 0x0f, 0xba, 0x0d, 0xbc, 0xa9, 0x37, 0x1b,
	0xf1, 0x3a, 0xc4, 0xa7, 0xf0, 0xa0, 0x12, 0x69, 0x49, 0xc1, 0xc0, 0xd6, 0x9a, 0x84, 0xfd, 0xf6,
	0x60, 0x1c, 0x89, 0xe4, 0xd2, 0x98, 0x9c, 0xd3, 0xaf, 0x92, 0xb4, 0xc1, 0x13, 0x38, 0xf8, 0x49,
	0xe6, 0x46, 0xc5, 0x2d, 0xbb, 0xcd, 0x6a, 0xc9, 0xb2, 0x90, 0x2d, 0xbd, 0x0e, 0xf1, 0x0d, 0x1c,
	0xde, 0xd8, 0x96, 0x3a, 0x18, 0x4e, 0x87, 0x33, 0xff, 0xec, 0x64, 0xbe, 0x31, 0x34, 0xdf, 0xb8,
	0xe1, 0x0e, 0x86, 0x08, 0xfb, 0x4b, 0x15, 0xdf, 0x06, 0xfb, 0x53, 0x6f, 0x76, 0xcc, 0x6d, 0xcc,
	0x5e, 0x81, 0x1f, 0x89, 0x64, 0x41, 0x2b, 0xa9, 0xa5, 0xca, 0x6a, 0x9f, 0x22, 0x4d, 0xd5, 0xda,
	0x76, 0x3f, 0xe2, 0x4d, 0xc2, 0xfe, 0x7a, 0x30, 0x8a, 0xce, 0xbf, 0x5e, 0xa8, 0x2c, 0x91, 0xd7,
	0x78, 0x0e, 0x63, 0x4d, 0x2b, 0x5e, 0xa6, 0xd4, 0x14, 0x74, 0xe0, 0xd9, 0xfe, 0xcf, 0xbb, 0xfd,
	0xaf, 0xba, 0x08, 0xbe, 0x45, 0xc0, 0x8f, 0x70, 0x7c, 0x4d, 0x6a, 0xf1, 0xd9, 0x09, 0x0c, 0xac,
	0xc0, 0x69, 0x57, 0xe0, 0xdb, 0xe6, 0x9d, 0xf7, 0xc0, 0x18, 0xc2, 0x13, 0x99, 0x73, 0xca, 0x4b,
	0x23, 0x8c, 0x54, 0x99, 0xd3, 0x68, 0x86, 0xf0, 0xb2, 0xab, 0xf1, 0x3d, 0xdc, 0x86, 0xf1, 0xfb,
	0xa8, 0xec, 0x03, 0x3c, 0xec, 0xf9, 0xc5, 0x31, 0x0c, 0xa4, 0xdb, 0xc0, 0x40, 0xc6, 0x18, 0xc0,
	0x21, 0x65, 0x62, 0x99, 0x52, 0x6c, 0x37, 0x70, 0xc4, 0x5d, 0xca, 0xde, 0x83, 0xdf, 0x71, 0xba,
	0x03, 0xf1, 0x13, 0xe0, 0x5d, 0x7b, 0x3b, 0xf0, 0x5f, 0xc3, 0xe3, 0xb0, 0x34, 0xed, 0x57, 0x91,
	0xce, 0x55, 0xa6, 0xa9, 0x86, 0x57, 0x54, 0xd4, 0x9b, 0xb4, 0x1a, 0x43, 0xee, 0xd2, 0xb3, 0x3f,
	0x1e, 0x40, 0x24, 0x92, 0xab, 0x66, 0x32, 0xb8, 0x00, 0xff, 0x4b, 0x25, 0x52, 0x77, 0x75, 0x93,
	0xee, 0xd4, 0xfa, 0x17, 0x39, 0x39, 0xdd, 0x7a, 0x73, 0xb7, 0xc2, 0xf6, 0xf0, 0x02, 0x46, 0xff,
	0x3d, 0xe0, 0xb3, 0x1e, 0xce, 0x5d, 0xcb, 0xe4, 0x45, 0xb7, 0x7c, 0xc7, 0x31, 0xdb, 0x5b, 0x1e,
	0xd8, 0xbf, 0xe9, 0xed, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xec, 0x98, 0xf4, 0x5a, 0x03,
	0x00, 0x00,
}
